### ISSUE TITLE
The plugin crashes due to invalid syntax error: path := os.getenv(key))

### ISSUE THREAD

**Issue by Nikita128** [alexanderjeurissen/ranger_devicons#98]
- [x] I've read the [guidelines for Contributing](https://github.com/alexanderjeurissen/ranger_devicons/blob/main/CONTRIBUTING.MD)

**Describe the bug**
Plugin crashes due to invalid syntax error.

**To Reproduce**
1. Download ranger_devicons repo to ~/.config/ranger/plugins/ranger_devicons
2. Add `default_linemode devicons` to rc.conf
3. Launch ranger

**Expected behavior**
Ranger emits no errors and displays icons.

**Screenshots**
I'll attach report from ranger launched in debug mode:
```
ranger version: ranger-master 
Python version: 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ranger/core/main.py", line 465, in load_settings
    module = importlib.import_module('plugins.' + plugin)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/developer/.config/ranger/plugins/ranger_devicons/__init__.py", line 4, in <module>
    from .devicons import *
  File "/home/developer/.config/ranger/plugins/ranger_devicons/devicons.py", line 20
    ] if (path := os.getenv(key))}
               ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ranger/core/main.py", line 122, in main
    load_settings(fm, args.clean)
  File "/usr/local/lib/python3.6/dist-packages/ranger/core/main.py", line 472, in load_settings
    fm.notify(ex_msg, bad=True)
  File "/usr/local/lib/python3.6/dist-packages/ranger/core/actions.py", line 177, in notify
    raise Exception(str(obj))
Exception: Error while loading plugin 'ranger_devicons'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Environment (please complete the following information):**
 - OS + version: [Ubuntu 18.04]
 - shell [bash]
 - shell version [4.4.20]

**Ranger devicons (please complete the following information):**
 - version / commit [ranger-master]
 - output of `tree ~/.config/ranger`
```
├── bookmarks
├── commands_full.py
├── commands.py
├── history
├── plugins
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── __init__.cpython-36.opt-1.pyc
│   │   └── __init__.cpython-36.pyc
│   └── ranger_devicons
│       ├── CONTRIBUTING.MD
│       ├── devicons.py
│       ├── __init__.py
│       ├── LICENSE
│       ├── LICENSE_NERDFONT
│       ├── __pycache__
│       │   ├── __init__.cpython-36.opt-1.pyc
│       │   └── __init__.cpython-36.pyc
│       ├── README.md
│       └── screenshot.png
├── rc.conf
├── scope.sh
└── tagged

4 directories, 19 files

```

**Additional context**
...

**Comment by XuehaiPan** [comment]
This issue has not been fixed yet. @alexanderjeurissen Can you take a look? Much appreciated.

**Comment by ferdinandyb** [comment]
What version is your python? `:=` was introduced in 3.8.

**Comment by XuehaiPan** [comment]
> What version is your python? `:=` was introduced in 3.8.

@ferdinandyb Ranger support Python 2.6, 2.7 and 3.x (3.1 ~ 3.10). See PR #96, it may fix this.
